### ISSUE TITLE
Support for AVR128DA Series?

### ISSUE THREAD

**Issue by davija** [MCUdude/MegaCoreX#100]
I know the AVR128DA is fairly new, but I had heard it was a near drop-in replacement for other chips in the series supported by this project.

Has this been tested on any of the AVR DA chips yet?

**Comment by MCUdude** [comment]
MegaCoreX doesn't support the AVR DA series, but [DxCore](https://github.com/SpenceKonde/DxCore) does!

**Comment by davija** [comment]
Awesome, thanks!

Sorry for hijacking your issues list! :)
