### ISSUE TITLE
analogReadResolution() function sets resolution wrong

### ISSUE THREAD

**Issue by PICboy** [MCUdude/MegaCoreX#101]
Hello MCUdude, I just found that if you write analogReadResolution(8),you will actualy set i to 10bits.
Solution:
at line 87 it should be ADC0.CTRLA|=ADC_RESSEL_bm;
and at line 91 it should be
ADC0. CTRLA&=~ADC_RESSEL_bm;
as ATmega4808 datasheet(page 406) says. 
If you can, please correct these 2 lines. 
Best regards from Serbia!

**Comment by MCUdude** [comment]
That is indeed a bug. Thanks for reporting!

**Comment by PICboy** [comment]
You're welcome! :)
Thank you for fast reply to my comment!
