### ISSUE TITLE
MegaCoreX seems not updated on PlatfromIO

### ISSUE THREAD

**Issue by tgtakaoka** [MCUdude/MegaCoreX#107]
I can't update MegaCoreX to 1.0.7 on PlatfromIO. Am I doing something wrong?

```
$ platformio platform update atmelmegaavr
Platform atmelmegaavr
--------
Updating platformio/atmelmegaavr              1.3.0                              [Up-to-date]
Updating platformio/toolchain-atmelavr        1.70300.191015 @ ~1.70300.0        [Up-to-date]
Updating platformio/framework-arduino-megaavr 1.8.6 @ ~1.8.6                     [Up-to-date]
Updating platformio/framework-arduino-megaavr-megacorex 1.0.5 @ ~1.0.5                     [Up-to-date]
```

**Comment by MCUdude** [comment]
Hi, great to see you back!

This is because the PlatformIO developers haven't updated the MegaCoreX package yet. There's nothing I can do about this, other than reminding them.

**Comment by tgtakaoka** [comment]
I noticed this because of Event library. It's available on arduino-cli but got error on platformio :).
I was wondering if there is something like `platformio package update` to push a revised platform.
Hope they will update the MegaCoreX sometime soon.

**Comment by MCUdude** [comment]
1.0.7 is now available for PlatformIO!
