### ISSUE TITLE
Taking over TCA0 for 16bits PWM

### ISSUE THREAD

**Issue by Emeric-dufour** [MCUdude/MegaCoreX#111]
Hello,

I am trying to take full control of the timer TCA0 while using the MegaCoreX on a nano every.
My code is the following :
'''
void Actuator_PWMDriver::timerA0_pwm_init(void) {	
	/* Initialize timer A0 for PWM */
	
	/* setup pins direction */
	PORTB.DIR |= PIN2_bm;
	PORTB.DIR |= PIN1_bm;
	PORTB.DIR |= PIN0_bm;

	TCA0.SPLIT.CTRLA = 0; //disable TCA0 and set divider to 1
	TCA0.SPLIT.CTRLESET = TCA_SPLIT_CMD_RESET_gc | 0x03; //set CMD to RESET to do a hard reset of TCA0 and enable for both halves.
	TCA0.SPLIT.CTRLD = 0;

	/* setup portmux */
	PORTMUX.TCAROUTEA |= PORTMUX_TCA0_PORTB_gc;

	// TCA0.SINGLE.CTRLA &= ~(TCA_SINGLE_ENABLE_bm);
	// TCA0.SPLIT.CTRLA &= ~(TCA_SPLIT_ENABLE_bm);
	// TCA0.SINGLE.CTRLA &= ~(TCA_SINGLE_CLKSEL_gm);
	// TCA0.SPLIT.CTRLA &= ~(TCA_SPLIT_CLKSEL_gm);
		
	/* TCA0 set Single slope PWM mode and enable all 3 PWM outputs */
	TCA0.SINGLE.CTRLB = TCA_SINGLE_CMP2EN_bm | TCA_SINGLE_CMP1EN_bm | TCA_SINGLE_CMP0EN_bm | TCA_SINGLE_WGMODE_DSBOTTOM_gc;
	// 1 << TCA_SINGLE_ALUPD_bp |

	/* TCA0 disable event counting */
	TCA0.SINGLE.EVCTRL &= ~(TCA_SINGLE_CNTEI_bm);

	/* TCA0 set the period */
	TCA0.SINGLE.PER = 255;
	TCA0.SINGLE.CMP0 = 127;
	TCA0.SINGLE.CMP1 = 127;
	TCA0.SINGLE.CMP2 = 127;
	// TCA0.SINGLE.PERBUF = 0xFFFF;
	// TCA0.SINGLE.CMP0BUF = 0x7fff;
	// TCA0.SINGLE.CMP1BUF = 0x7fff;
	// TCA0.SINGLE.CMP2BUF = 0x7fff;

	/* TCA0 enable overflow interrupt */
	TCA0.SINGLE.INTCTRL |= TCA_SINGLE_OVF_bm;

	/* TCA0 set the pre-scaler */
	TCA0.SINGLE.CTRLA = TCA_SINGLE_CLKSEL_DIV1_gc;
	
	/* start the timer */
	TCA0.SINGLE.CTRLA |= TCA_SINGLE_ENABLE_bm;
} 
'''

And everytime I use "TCA0.SPLIT.CTRLD = 0;" to bypass the split mode setup by the core at start-up, my TCA0 pins stop sending the PWM signal. And if I just comment the line, I am back to proper PWM but with only 8bit split mode.

Any ideas as to how I could take full control ?

Thanks a lot!

**Comment by MCUdude** [comment]
I'll recommend you this write-up from the megaTinyCore repo. It's written for the tinyAVR-0 and -1 series, but the TCA timer is still the same.
https://github.com/SpenceKonde/megaTinyCore/blob/master/megaavr/extras/TakingOverTCA0.md
