### ISSUE TITLE
Analogread A0 (PD0) reads PF4

### ISSUE THREAD

**Issue by classiphil** [MCUdude/MegaCoreX#121]
Am I doing something wrong? When I compile the example AnalogreadSerial Sketch which should read A0 (PD0) on a 4809 on a breadboard the TX Port presents the readings of PF4? (I chose no bootloader, 40Pin, 16 MHz and set the fuses. Programming with Arduino (JTAG2UPDI).. )

**Comment by classiphil** [comment]
Found it!

I have to use analogread(0) not (A0) as I did.

**Comment by MCUdude** [comment]
> I have to use analogRead(0) not (A0) as I did.

Thanks for taking a look at it. It is certainly a bug I'll look into. For reference, what pinout option did you use when you compiled your code?

**Comment by classiphil** [comment]
40 Pin

**Comment by MCUdude** [comment]
The issue should now be fixed and will be available in the next release. The bug affected A0 and A1.
