### ISSUE TITLE
Is JTAG2UPDI a reliable programmer for ATMEGA 4809/3209??

### ISSUE THREAD

**Issue by Hamza-arch** [MCUdude/MegaCoreX#129]
Hi,
Thank you for making such a great MegaCorex. I am looking for a suitable chip for my robotic hand application. It needs 26 digital pins and 4 analog pins. 5 of digital pins are interrupts and SPI pins are also included in 26 pins. I believe ATMEGA 4809 series has all these requirements which are not available in any similar micro-controller. I have tried previosly ATMEGA16/32, but they did not fulfill the interrupts requirements.

My question is JTAG2UPDI a reliable programmer for my application or should I use microUPDI programmer. I use arduino for programming. The issue is I am from Pakistan and it is difficult to get all these components. I want to buy a UPDI programmer to be safe but Atmega4809/3209 chips are not available and also there are shipping issues. I have found the chips on arrow.com, but it does not have microUPDI programmer. Can anyone recommend me a website from which I can  found all the components or is it totally okay and relaible to use JTAG2UPDI programmer, so I can easily order the chips.
Thank you very much.

**Comment by tgsavs69** [comment]
Hello,

From my personal experience, JTAG2UPDI seems to be pretty reliable. I used ATmega4809 on a custom board and for the programmer, I followed this tutorial: https://create.arduino.cc/projecthub/john-bradnam/create-your-own-updi-programmer-1e55f1

If you have any question, don't hesitate to ask them!

Yours faithfully,
Bancila Sorin

**Comment by Hamza-arch** [comment]
Thank you soo much for your guidance.

**Comment by SpenceKonde** [comment]
Jtag2updi, imo, is a bit flaky on individual programming attempts but
generally usable. My cores use SerialUPDI

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: ***@***.***
