### ISSUE TITLE
I suggest giving the timer usage in the documentation

### ISSUE THREAD

**Issue by technoblogy** [MCUdude/MegaCoreX#165]
It would be good to have a sentence in the documentation stating which timers are used by default for Arduino functions; I believe it's TCB2 for millis() and delay(), but it would be good to have a statement to that effect.

**Comment by SpenceKonde** [comment]
Is someone spoiled by my essay-length documentation?

https://github.com/SpenceKonde/DxCore/blob/master/megaavr/extras/Ref_Timers.md

**Comment by technoblogy** [comment]
I'd settle for something less definitive than that!

**Comment by cattledogGH** [comment]
The Timer used for millis() is given in the variants files with pins_arduino.h.

> I believe it's TCB2 for millis() and delay()

Depends on the processor/board. For the Nano Every and UnoWiFi using the 4809 its TCB3.

**Comment by MCUdude** [comment]
Resolved in [8dca08](https://github.com/MCUdude/MegaCoreX/commit/8dca088f6f287fa83e43d2a85b883e3838c5318b)
