### ISSUE TITLE
4809 Serial3 undefined

### ISSUE THREAD

**Issue by mabwindsor** [MCUdude/MegaCoreX#178]
I have a custom board using a 4809.  Programming is on MS visual Studio, with VisualMicro IDE 
 The programming and functions have been perfect until last Saturday April 29 2023.  
The project uses all the 4 ports, but now it refuses to recognize Serial3.
If I use the '3209 chip model it compiles perfectly.
I have replaced the Microsoft VS, and the Visual studio, same result.

However, if I use the Arduino IDE, the project compiles.

**Comment by mabwindsor** [comment]
[4809_Serial3_problem.txt](https://github.com/MCUdude/MegaCoreX/files/11385137/4809_Serial3_problem.txt)
MB

**Comment by MCUdude** [comment]
Here is a clue:

```
Core Include Paths
Include Path "file:///C:/Program%20Files%20(x86)/Arduino/hardware/MegaCoreX-master/megaavr/cores/coreX-corefiles"
Include Path "file:///C:/Program%20Files%20(x86)/Arduino/hardware/MegaCoreX-master/megaavr/variants/40pin-standard"
```

You're building for the `40pin-standard` variant, but the 40-pin chip doesn't have a fourth serial port, only Serial0, Serial1, and Serial2. Try building for the the 48-pin standard pinout instead.

**Comment by mabwindsor** [comment]
Thank you, I thought it was me making an error. The Visual Micro interface
does not allow a choice of packages.
I will take the matter up with them.
Again, thanks for your help.

Mike B

**Comment by mabwindsor** [comment]
Problem solved! Visual Micro does allow package selection.Somehow the selection got changed to the 40pin package, and I didn’t notice.Your analysis of the problem led me to checkout all the settings, and that solved the problem.Many thanks for the help. MikeB Sent from Mail for Windows From: HansSent: May 4, 2023 5:00 AMTo: MCUdude/MegaCoreXCc: mabwindsor; State changeSubject: Re: [MCUdude/MegaCoreX] 4809 Serial3 undefined (Issue #178) I think it should be possible to change the desired pinout in Visual Micro as well?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
