### ISSUE TITLE
Any PortManipulation available?

### ISSUE THREAD

**Issue by mdelain** [MCUdude/MegaCoreX#181]
Hi,
I'm discovering this core today and I'm starting to read up on it.
I haven't found an equivalent to [portRead()](https://github.com/MCUdude/MiniCore/blob/master/Wiring_reference.md#portread) on MiniCore - is it hidden somewhere or is it not possible on this architecture?
thanks!

**Comment by SpenceKonde** [comment]
https://github.com/SpenceKonde/megaTinyCore/blob/master/megaavr/extras/Ref_DirectPortManipulation.md if you can follow it.

**Comment by mdelain** [comment]
Awsome, thanks!!
