### ISSUE TITLE
analogWriteFrequency(kHz) to analogWriteFrequency(Hz)

### ISSUE THREAD

**Issue by ltwin8** [MCUdude/MegaCoreX#184]
hello, is it possible to change analogWriteFrequency(kHz) to accept Hz?

to avoid bricking existing code it could be like if value <=64 interpret as kHz, else interpret as Hz

PWM frequencys below 1 kHz would be useful in some cases like driving lighting to avoid high frequency and allow for slower edges (EMI friendlier)

**Comment by MCUdude** [comment]
Sorry, but setting arbitrary PWM frequencies is not possible. You can try setting a lower main clock frequency (something lower than the default 16 MHz) and play around with the `TCA0.SPLIT.CTRLA` register to see what yo can achieve.

https://github.com/MCUdude/MegaCoreX/blob/d0f0eff16e6d214397e13ca21dd24e53046e42e8/megaavr/cores/coreX-corefiles/wiring_analog.c#L196-L230
