### ISSUE TITLE
Serial.swap() does not work

### ISSUE THREAD

**Issue by egilkv** [MCUdude/MegaCoreX#23]
This is due to the code for manipulating the bits in PORTMUX.USARTROUTEA not being correct. Fixed easily enough.

However, there is another more major issue with the Serial.swap mechanism, which is that it will in fact define the unswapped pins first, then set them to inputs and define the swapped pins. This is very uinhealty, and can lead to ugly bugs depending on the sequence of pin definitions. Could also create problems for hardware, since the unswapped pins will swing to Vcc for a show period.
All in all a bad design, which I believe may have been inherited for ESP code? 

Anyway, to fix this of sorts, I have made a change to swap() so that it can be invoked before begin(), or after. This should not break any existing code. 

However, it would be much cleaner to instead have pin swop status as a third argument to begin(), for instance. 

Anyway, the fix is here: https://github.com/MCUdude/MegaCoreX/pull/22

**Comment by MCUdude** [comment]
Fixed in 40a59cb
