### ISSUE TITLE
Ugly bug in serial transmit interrupt

### ISSUE THREAD

**Issue by egilkv** [MCUdude/MegaCoreX#26]
This bug is inherited from the Arduino megaavr package, it is not in the original avr. The offending line is this:

`while(!((*_hwserial_module).STATUS & USART_DREIF_bm));`

It causes the CPU to stay put in the interrupt handler until the character is actually transmitted. Not only does this waste a lot of CPU cycles needlessly, since further serial interrupts are disabled at this time, it can miss a lot of interrupts on other peripherals. It is more of a problem the lower the baudrate on the transmitting channel.

It is easily reproduced by transmitting continuously on a slow baudrate on one serial channels, while receiving at a higher baudrate on another channels. Also, when transmitting on slow baudrates, the available CPU capacity will also be significantly reduced. 

I am surprised that such a bug slipped though 'the net'. There are also some other 'interesting' things with the new driver, so I plan to review and revise as needed. There is also an issue with critical regions in the old driver that is not resolved in the new. 

But this one thing is urgent, and can and should be fixed first. I have created a branch called 'Upstream' for this: https://github.com/MCUdude/MegaCoreX/pull/25

**Comment by MCUdude** [comment]
#25 merged!
