### ISSUE TITLE
Code formatting is all over the place

### ISSUE THREAD

**Issue by MCUdude** [MCUdude/MegaCoreX#37]
We need some rules on how code should be formatted. The official Arduino megaAVR code doesn't have this either, which results in a big mess.

**Comment by uzi18** [comment]
try use https://github.com/uncrustify/uncrustify

example config:
https://github.com/letscontrolit/ESPEasy/blob/mega/uncrustify.cfg

**Comment by MCUdude** [comment]
@per1234 would you like to look into this? 🙂

**Comment by MCUdude** [comment]
Fixed in e54b7f3
