### ISSUE TITLE
Optiboot filenames are in wrong case

### ISSUE THREAD

**Issue by tgtakaoka** [MCUdude/MegaCoreX#57]
The optiboot hex files has "Optiboot_" uppercase prefixed filenames, but in boards.txt bootloader.file names are specified with "optiboot_" lowercase prefixed.

**Comment by tgtakaoka** [comment]
On a case sensitive filesystem host, such as Linux, burning bootloader definitely fails :(.

**Comment by MCUdude** [comment]
Huh, I wonder how this obvious bug slipped through. Anyways, it's fixed now. Thanks for reporting!
