### ISSUE TITLE
ATmega4809P needs special setup for missing ports.

### ISSUE THREAD

**Issue by tgtakaoka** [MCUdude/MegaCoreX#65]
In the latest [ATmega4809 datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/ATmega4808-4809-Data-Sheet-DS40002173A.pdf), it has a Important note on the first page.

> **Important**:  The 40-pin version of the ATmega4809 is using the die of the 48-pin ATmega4809 but offers fewer connected pads. For this reason, the pins PB[5:0] and PC[7:6] must be disabled (INPUT_DISABLE) or enable pull-ups (PULLUPEN)

So, it may be great if we can have special port settings for 40-pin version of variant in MegaCoreX's core.
WDYT?

**Comment by MCUdude** [comment]
If the pins are there on the die, but simply not broken out, why would this be any different that unused IO pins on a TQFP48 ATmega4809?

The reason why I'm a bit hesitant is that I'm planning for PlatformIO support, and I want as few extra options in the configuration file as possible. Even though Microchip recommends disabling these pins, does it _really_ make any difference as long as these pins are not being read?

**Comment by tgtakaoka** [comment]
Hmm, suppose if an inattentive PDIP40 ATmega4809P user sets up their project with standard-48pin variant and doesn't carefully read the datasheet, they may easily miss to initialize un-broken-out pins, because there is no physical pins related and easily overlook.

I think those uninitialized pins may cause issues not easily identifiable, such as slightly increasing current consumption, or noise on the port sporadically, we usually seen 
It also may bite us in some future ;).

ATmega4809P is the sole DIP parts in megaAVR-0 series so far, and given the Arduino DIY community's preference for DIP package parts, having and maintaining another one configuration will be paid off, I think.

**Comment by MCUdude** [comment]
@tgtakaoka I've now pushed a dedicated DIP-40 pinout. I don't actually own an ATmega4809 DIP-40 so could you test it to see if it works. Note that the pinout has been edited to match the other targets. Previously, pin 8-13 + 20 and 21 were not available. Now they are, and the highest pin number is 32 instead of 41.

**Comment by tgtakaoka** [comment]
Wohoo! Thanks a lot to reconsider having 40pin-standard!
I confirmed that (with ATmega4809P)
  - example/basic/blink works fine with internal 20MHz.
  - optiboot (UART1 default pin) with internal 20MHz, and example/communication/ASCIITable on Serial1 & 115,200bps works with no issue.
though I don't have test every digital IO, analog IO, and timer etc. so far.
But definitely I'll let you know if I find an issue.

Thanks again!

**Comment by MCUdude** [comment]
It should be OK now. Please reopen or create a new issue if you're experiencing issues!
