### ISSUE TITLE
bool conversion error digitalWrite(DCF_LED_Pin, !digitalRead(DCF_PIN));  

### ISSUE THREAD

**Issue by ednieuw** [MCUdude/MegaCoreX#69]
There is a conversion error that runs well with the Arduino Nano every board

 digitalWrite(DCF_LED_Pin, !digitalRead(DCF_PIN));  
Error -->   cannot convert 'bool' to 'PinStatus' for argument '2' to 'void digitalWrite(pin_size_t, PinStatus)'

digitalWrite(DCF_LED_Pin, 1-digitalRead(DCF_PIN));    // --> Works

See also
https://github.com/ednieuw/DCFtiny-clock/tree/master/DCF_HC12TransmitterV38d

**Comment by rocketscream** [comment]
Another workaround is if you use the CHANGE constant instead of reading the pin status.

**Comment by MCUdude** [comment]
This will be fixed in the next release, v1.0.2, which will be available very soon. Meanwhile, you can use CHANGE instead.

**Comment by ednieuw** [comment]
Thanks!



——————————————————————————————————-
Ed Nieuwenhuys |  Badhoevedorp, The Netherlands |  ednieuw@xs4all.nl   
https://ednieuw.home.xs4all.nl
——————————————————————————————————-

**Comment by MCUdude** [comment]
Boards manager release 1.0.2 is now available. Please install this version and see if it fixes you issue

**Comment by ednieuw** [comment]
Checked. Errors are gone.
