### ISSUE TITLE
Multiple definition of `initVariant' in v1.0.2

### ISSUE THREAD

**Issue by rocketscream** [MCUdude/MegaCoreX#70]
Error when compiling using 1.0.2 using the blink example for ATMega4808.
Errors:
`wiring.c.o (symbol from plugin): In function `initVariant':
(.text+0x0): multiple definition of `initVariant'
/tmp/arduino_build_850708/sketch/Blink.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
wiring_analog.c.o (symbol from plugin): In function `initVariant':
(.text+0x0): multiple definition of `initVariant'
/tmp/arduino_build_850708/sketch/Blink.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
wiring_digital.c.o (symbol from plugin): In function `digital_pin_to_timer':
(.text+0x0): multiple definition of `initVariant'
/tmp/arduino_build_850708/sketch/Blink.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
main.cpp.o (symbol from plugin): In function `initVariant':
(.text+0x0): multiple definition of `initVariant'
/tmp/arduino_build_850708/sketch/Blink.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board ATmega4808.`

**Comment by MCUdude** [comment]
Ah, damn it! This is how it goes when the repo has no CI implemented 🙁 
There is a line missing in the pins_arduino.h for the 32-pin parts. I'll fix it right away and release 1.0.3.
