### ISSUE TITLE
comments for digital_pin_to_* say LED_BUILTIN is on wrong pin

### ISSUE THREAD

**Issue by SpenceKonde** [MCUdude/MegaCoreX#72]
In pins_arduino.h, LED_BUILTIN is set to PIN_PA7, however later in the same file, the comments on the digital_pin_to_* tables list it as being on PF5 or PD3 (depending on number of pins for part), rather than PA7

**Comment by MCUdude** [comment]
Thanks for reporting! You're clearly doing a deep dive, and that's definitely a good thing. Feel free to use as much as you like. The more similar our cores can be, the better
