### ISSUE TITLE
Add support for 5MHz and 10MHz operation

### ISSUE THREAD

**Issue by SpenceKonde** [MCUdude/MegaCoreX#74]
These are the maximum operating frequencies guaranteed to work with specified BOD voltages (per electrical specifications of datasheet); if a user wishes to have BOD enabled and operate at less than 4.5v, they are forced to use the processor below it's capabilities when using this core. These frequencies should be added to the core. See megaTinyCore for the combination of bitshifts to provide acceptable micros return time and accuracy when using these frequencies.

**Comment by MCUdude** [comment]
I'll call that an edge case, but why not?
