### ISSUE TITLE
Does reassigning LED_BUILTIN to another pin also carry over the LED flashes during hardware reset?

### ISSUE THREAD

**Issue by sideswiper22** [MCUdude/MegaCoreX#82]
Hello, so I'm designing a development board using your core and I would like to ask if reassigning the LED_BUILTIN in pins.h to another pin also carries over the LED flash when the chip is hardware reset? Connecting my status LED to pin 7 doesn't seem to be an intuitive pin in my case with my pcb layout.

**Comment by MCUdude** [comment]
The `LED_BUILTIN` macro is just, *a macro*. It's just a placeholder for an arbitrary number.

https://github.com/MCUdude/MegaCoreX/blob/e6c658af37daa0cf75da32dbd1bab051db64f585/megaavr/variants/48pin-standard/pins_arduino.h#L82

If you want the bootloader LED flash pin to be something else than PA7, you'll have to compile your own bootloader binary.

With a properly set up environment, the build command is:

```bash
make mega0 UARTTX=A0 TIMEOUT=1 LED=A7 BAUD_RATE=115200
```
