### ISSUE TITLE
Bootloader UART options should apply to Arduino Core as well

### ISSUE THREAD

**Issue by WestfW** [MCUdude/MegaCoreX#90]
It would be nice (for me, anyway) if when you select the menu item that causes the bootloader to be "optiboot UART0 (alternate pins)" that the Arduino core ALSO used the alternate pin assignments for UART0...

It might be nice if the bootloader uart became "Serial", even if it wasn't UART0?

**Comment by MCUdude** [comment]
It's a good idea, but this logic would be difficult to apply to the PlatformIO implementation I'm about to start working on. PlatformIO is important and a priority, and I'd prefer to keep the PlatformIO and Arduino IDE implementation as similar as possible.
