### ISSUE TITLE
Small issue Curiosity pinout

### ISSUE THREAD

**Issue by sstaub** [MCUdude/MegaCoreX#93]
There is a small issue in the Curiosity Nano pinout diagram, the on board LED is connected to Pin PF5 not PA7.

**Comment by classiphil** [comment]
Funnily enough, when I try to read A0 (PD0) it reads PF4?

**Comment by MCUdude** [comment]
> There is a small issue in the Curiosity Nano pinout diagram, the on board LED is connected to Pin PF5 not PA7.

The LED labels are originally there to indicate that that is the default LED pin that LED_BUILTIN refers to. But it is a bit misleading and should be removed.

> Funnily enough, when I try to read A0 (PD0) it reads PF4?

Sounds weird. Can you post your code?

**Comment by classiphil** [comment]
It was my mistake. I typed Analogread(A0) instead of (0).

Interesting though why (A0) leads to PF4...
Maybe A0 is interpreted as 100 (Hex A and a 0) so it is a binary 4?!? :D

**Comment by MCUdude** [comment]
That shouldn't be possible. Be I need to know if you're using the 40-pin or 48-pin pinout.

**Comment by classiphil** [comment]
The 40 Pin.
