### ISSUE TITLE
Logic.h handles enable protection ungracefully.

### ISSUE THREAD

**Issue by SpenceKonde** [MCUdude/MegaCoreX#98]
First, none of the LUTs can be enabled or disabled while the CCL in general is "enabled". This is marked as errata - but, like the port override on the TWI pins, and the open drain mode of USARTs, it's like this for EVERY SINGLE PART WITH A CCL THAT HAS BEEN RELEASED! The requirement that the CCL be stopped should be mentioned in Readme.md.

Secondly, each individual LUT can't be reconfigured in any meaningful way while enabled....

So right now with Logic.h, if I want to reconfigure a CCL unit, I would have to:

```
Logic::stop();
Logic0.enable=false;
Logic0.init(); //apply the disabling
// reconfigure the LUT
Logic0.enable=true;
Logic0.init();
Logic::start();
```

I think keeping the stop and start of the whole CCL explicit is fine (probably good)... but having to explicitly disable the LUT, init() it, then reconfigure and init() it again to re-enable it... that's... not so great. 
In DxCore, I am adding  `block.LUTCTRLA = 0;` to the start of init() to address this. It seems to work.
Now, I can do:

```
//reconfigure the LUT
//up here, before turning anything off. 
Logic::stop();
Logic0.init();
Logic::start();
```

**Comment by MCUdude** [comment]
> In DxCore, I am adding  block.LUTCTRLA = 0; to the start of init() to address this. It seems to work.

Good idea! I'll get around and implement this.
